import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateLoanPDF = (loan: any, installments: any[]) => {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  // -----------------------------
  // HEADER
  // -----------------------------
  doc.setFontSize(18);
  doc.setTextColor(0, 128, 0);
  doc.text("ZIST SOFT LOAN PROFILE", 105, 15, { align: "center" });

  doc.setLineWidth(0.5);
  doc.line(15, 20, 195, 20);

  // -----------------------------
  // LOAN BASIC DETAILS
  // -----------------------------
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text("Loan Details", 15, 30);

  doc.setFontSize(11);
  doc.text(`Name: ${loan.name}`, 15, 40);
  doc.text(`Parentage: ${loan.parentage}`, 15, 48);
  doc.text(`Phone: ${loan.phone}`, 15, 56);
  doc.text(`Address: ${loan.address}`, 15, 64);

  doc.text(`Loan Amount: ₹${loan.amount.toLocaleString()}`, 120, 40);
  doc.text(`Cheque No: ${loan.cheque_no}`, 120, 48);
  doc.text(`Status: ${loan.status}`, 120, 56);
  doc.text(
    `Recommendation: ${loan.recommendation || "---"}`,
    120,
    64
  );

  doc.line(15, 70, 195, 70);

  // -----------------------------
  // INSTALLMENT TABLE
  // -----------------------------
  doc.setFontSize(14);
  doc.text("Installment History", 15, 80);

  if (installments.length === 0) {
    doc.setFontSize(11);
    doc.text("No installments recorded.", 15, 90);
  } else {
    const tableData = installments.map((ins, index) => [
      index + 1,
      ins.amount,
      ins.payment_date,
      ins.notes || "---",
    ]);

    autoTable(doc, {
      startY: 85,
      head: [["#", "Amount", "Date", "Notes"]],
      body: tableData,
      theme: "grid",
      styles: { fontSize: 11 },
      headStyles: { fillColor: [0, 128, 0] },
    });
  }

  // -----------------------------
  // TOTALS
  // -----------------------------
  const totalPaid = installments.reduce((sum, i) => sum + Number(i.amount), 0);
  const balance = loan.amount - totalPaid;

  let finalY = doc.lastAutoTable ? doc.lastAutoTable.finalY : 105;

  doc.setFontSize(13);
  doc.text("Summary", 15, finalY + 15);

  doc.setFontSize(11);
  doc.text(`Total Paid: ₹${totalPaid.toLocaleString()}`, 15, finalY + 25);
  doc.text(`Outstanding Balance: ₹${balance.toLocaleString()}`, 15, finalY + 33);

  doc.line(15, finalY + 40, 195, finalY + 40);

  // -----------------------------
  // FOOTER
  // -----------------------------
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(
    "Generated by ZIST Beneficiary & Loan Management System",
    105,
    287,
    { align: "center" }
  );

  // -----------------------------
  // SAVE PDF
  // -----------------------------
  doc.save(`SoftLoan_${loan.name}.pdf`);
};
export default function LoanPDF() {
  return <></>;
}

